import type { DemoLandingContent } from "./demo-landing-page";

export const demoLandingPages = {
  peluqueria: {
    businessName: "Peluquería Brillo Norte",
    eyebrow: "Cortes, color y peinados con agenda simple",
    headline: "Una peluquería de barrio que se ve profesional desde el primer clic.",
    subheadline: "Mostrá tus servicios, precios orientativos y botón directo a WhatsApp para transformar visitas en reservas.",
    services: ["Corte femenino y masculino", "Coloración y reflejos", "Peinados para eventos", "Tratamientos capilares"],
    benefits: ["Ordena la oferta para que el cliente entienda rápido qué puede pedir.", "Reduce mensajes repetidos con servicios claros y llamada a la acción directa.", "Permite enviar una demo concreta por WhatsApp, Instagram o Facebook."],
    proofPoints: ["Agenda por WhatsApp", "Servicios visibles", "Diseño listo para redes"],
    audience: "Demo peluquería",
  },
  estetica: {
    businessName: "Estética Alma Serena",
    eyebrow: "Tratamientos corporales, faciales y bienestar",
    headline: "Una landing para vender estética con confianza y claridad.",
    subheadline: "Ideal para mostrar tratamientos, beneficios y reservas sin prometer resultados médicos ni usar datos reales.",
    services: ["Limpieza facial", "Masajes modeladores", "Drenaje linfático", "Radiofrecuencia estética"],
    benefits: ["Presenta tratamientos con lenguaje comercial pero prudente.", "Genera confianza sin depender solo de publicaciones sueltas en redes.", "Lleva al cliente directo a consultar disponibilidad por WhatsApp."],
    proofPoints: ["Demo sin datos reales", "CTA de consulta", "Ideal para Instagram"],
    audience: "Demo estética",
  },
  tecnicoReparaciones: {
    businessName: "Técnico Rápido UY",
    eyebrow: "Reparaciones y asistencia a domicilio",
    headline: "Una página simple para recibir pedidos de reparación todos los días.",
    subheadline: "Mostrá qué arreglás, zonas de atención y un botón de contacto para presupuestos rápidos.",
    services: ["Reparación de electrodomésticos", "Instalaciones básicas", "Diagnóstico a domicilio", "Mantenimiento preventivo"],
    benefits: ["Convierte consultas sueltas en pedidos con mejor contexto.", "Ayuda a filtrar trabajos por zona, urgencia y tipo de reparación.", "Da presencia profesional aunque el negocio sea unipersonal."],
    proofPoints: ["Presupuesto por WhatsApp", "Zonas visibles", "Servicios claros"],
    audience: "Demo técnico",
  },
  limpieza: {
    businessName: "Limpieza Clara Hogar",
    eyebrow: "Limpieza para casas, oficinas y locales",
    headline: "Una landing para vender servicios de limpieza sin explicar todo de cero.",
    subheadline: "El cliente ve qué incluye el servicio, cuándo consultar y cómo pedir una cotización simple.",
    services: ["Limpieza semanal", "Limpieza profunda", "Oficinas pequeñas", "Final de obra liviano"],
    benefits: ["Aclara el alcance del servicio antes de recibir consultas.", "Permite separar limpieza recurrente, profunda y comercial.", "Mejora la confianza con una presentación clara y ordenada."],
    proofPoints: ["Cotización rápida", "Servicios por categoría", "Contacto directo"],
    audience: "Demo limpieza",
  },
  delivery: {
    businessName: "Delivery Punto Express",
    eyebrow: "Envíos locales y mandados rápidos",
    headline: "Una página para recibir pedidos de delivery local sin app compleja.",
    subheadline: "Perfecta para mostrar zonas, horarios y tipos de envíos con contacto directo por WhatsApp.",
    services: ["Mandados barriales", "Retiro y entrega", "Envíos programados", "Compras pequeñas"],
    benefits: ["Explica zonas y horarios antes del contacto.", "Reduce dudas con ejemplos concretos de pedidos.", "Sirve para vender un servicio local sin desarrollar una app completa."],
    proofPoints: ["Zonas y horarios", "Pedidos por WhatsApp", "Demo rápida"],
    audience: "Demo delivery",
  },
} satisfies Record<string, DemoLandingContent>;
